### ISSUE TITLE
Get in touch : access to IOOS Code Sprint ?

### ISSUE THREAD

**Issue by pp-mo** [MathewBiddle/MathewBiddle#1]
Hi @MathewBiddle 
Just sent you an email about getting access to the IOOS code sprint, but got an out-of-office reply !

So copied here ...

Hi Matthew

Can you help me  connect to the ongoing IOOS code sprint on Zoom/Slack ?
I was encouraged by Filipe Fernandez (https://github.com/ocefpaf) to get involved (for reasons below).
But unfortunately I’ve been a bit out of it, since I missed getting connected to the group before this.

I work in the Uk MetOffice, in a software group providing Python tooling for scientific use (production and research)
– so I’m a software engineer not a scientist or modeller,
There were two suggestions for involvement :
(1)	As in the following issue : https://github.com/ioos/ioos-code-sprint/issues/6
I have recently developed a general-purpose Python UGRID checker tool, [ugrid-checks](https://github.com/pp-mo/ugrid-checks#readme), and we are considering connecting this to the IOOS compliance-checker
- see https://github.com/pp-mo/ugrid-checks/issues/44
Status : I have some draft code to link the 2, could collaborate with someone to draft a linking package
(2)	(also in the above discussion)
My group works on [Iris](https://github.com/SciTools/iris), to which we have just added UGRID read/write and internal “data cube” representation.
We are currently adding Iris regridding based on ESMF, 
and a new package, [GeoVista](https://geovista.readthedocs.io/en/latest/), which bridges geolocated data (e.g. Iris or xarray) to mesh analytics and 3D visualisation in [PyVista](https://www.pyvista.org/) (and hence VTK).
So, Filipe thought some of this might be good for a lightning talk ?

AFAICT, our efforts might have relevance in the following areas :
•	Python tooling interoperabililty
•	File formats, data standardisation and format-agnostic data management
•	visualisation, VTK
•	large-data analysis, parallel and out-of-core processing (VTK and [Dask](https://docs.dask.org/en/stable/))

Thanks!
Regards, Patrick

**Comment by MathewBiddle** [comment]
Just sent you something.
